basePath: /api
definitions:
  entities.User:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  entities.UserResponse:
    properties:
      createAt:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: REST API base on Clean Arch.
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: get a new token by login
      parameters:
      - description: user name and password
        in: body
        name: Token
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: User authorization and generate token
      tags:
      - Token
  /v1/users:
    get:
      consumes:
      - application/json
      parameters:
      - default: 10
        description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - default: 0
        description: Offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.UserResponse'
            type: array
      security:
      - Bearer: []
      summary: Get user list
      tags:
      - User Account
    post:
      consumes:
      - application/json
      parameters:
      - description: user name and password
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      security:
      - Bearer: []
      summary: Create user account
      tags:
      - User Account
  /v1/users/{user_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - Bearer: []
      summary: Delete user
      tags:
      - User Account
  /v1/users/{user_name}/reset:
    put:
      consumes:
      - application/json
      parameters:
      - description: User Name
        in: path
        name: user_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - Bearer: []
      summary: Reset user password
      tags:
      - User Account
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
