basePath: /api
definitions:
  entities.User:
    properties:
      id:
        type: integer
      name:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: GIN JWT API
  version: "1.0"
paths:
  /token:
    post:
      consumes:
      - application/json
      description: create a new token by user
      parameters:
      - description: user name and password
        in: body
        name: Token
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Generate token
      tags:
      - Token
  /users:
    post:
      consumes:
      - application/json
      description: create user account
      parameters:
      - description: user name and password
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Create user account
      tags:
      - User Account
swagger: "2.0"
