basePath: /api
definitions:
  entities.User:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: REST API base on Clean Arch
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: get a new token by login
      parameters:
      - description: user name and password
        in: body
        name: Token
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: User authorization and generate token
      tags:
      - Token
  /v1/users:
    post:
      consumes:
      - application/json
      description: create user account
      parameters:
      - description: user name and password
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      security:
      - Bearer: []
      summary: Create user account
      tags:
      - User Account
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
